export const AGUA_COPOS = 10
export const AGUA_ML_POR_COPO = 250

export const REFEICOES = [
  {
    id: 'desjejum',
    label: 'Desjejum',
    horario: 'Opcional — ao acordar',
    icon: '🌅',
    tipo: 'fixo',
    descricao: 'Shot imunidade: 1 limão espremido + 1 col café rasa de gengibre em pó ou ralado + 1 col café rasa de cúrcuma em pó + 15 gotas de própolis',
    opcoes: null,
  },
  {
    id: 'cafe',
    label: 'Café da Manhã',
    horario: 'Manhã',
    icon: '☕',
    tipo: 'opcoes',
    descricao: 'Escolha uma das opções:',
    opcoes: [
      'Pão integral (2 fatias) ou pão francês + ovo mexido (3 unidades) ou 4 fatias de queijo branco derretido + suco de laranja',
      'Crepioca (3 col tapioca + 1 col chá de chia + 2 ovos) + banana',
      'Banana com aveia e pasta de amendoim + Iogurte (Verde Campo Whey, Moo, Yorgus ou Iogurte Natural)',
      'Shake: 1 scoop whey protein + fruta + 1 col sopa de farelo de aveia + leite (200 mL)',
    ],
  },
  {
    id: 'lanche_manha',
    label: 'Lanche da Manhã',
    horario: 'Pré-treino',
    icon: '🥪',
    tipo: 'opcoes',
    descricao: 'Pré-treino — escolha uma opção:',
    opcoes: [
      'Sanduíche: 2 fatias de pão integral + frango desfiado com queijo cottage (2 col sopa)',
      'Sanduíche: 2 fatias de pão integral + 4 fatias de rosbife + tomate + rúcula',
      'Crepioca: 2 col sopa de tapioca + 2 ovos + queijo branco',
    ],
  },
  {
    id: 'almoco',
    label: 'Almoço',
    horario: 'Almoço',
    icon: '🍽️',
    tipo: 'estruturado',
    descricao: 'Monte o prato:',
    opcoes: null,
    estrutura: [
      { nome: 'Proteína', detalhe: '150–180g de carne, frango ou peixe (assado ou cozido de preferência)' },
      { nome: 'Carboidrato', detalhe: 'Tubérculos (batata doce, inhame, cará — 5 col sopa) ou abóbora assada (4 pedaços grandes) ou quinua cozida (8 col sopa) ou arroz integral com feijão (8 col sopa de cada)' },
      { nome: 'Legumes cozidos', detalhe: '1 xícara — variar sempre que possível' },
      { nome: 'Salada', detalhe: 'Equivalente a prato de sobremesa — folhas verdes escuras (rúcula, agrião) + mix de castanhas e sementes + bastante azeite de oliva' },
      { nome: 'Sobremesa', detalhe: 'Fruta + 1 col sopa de pasta de amendoim ou chocolate amargo (20g)' },
    ],
    opcoesAlternativas: [
      'Macarrão bolonhesa: prato de sopa cheio + prato de sobremesa de salada diversificada',
      'Strogonoff: 1 concha grande cheia + 5 col sopa de arroz + 1 xíc de legumes',
      'Torta de frango: ~350g + legumes ou salada diversificada',
    ],
  },
  {
    id: 'lanche_tarde1',
    label: 'Lanche da Tarde 1',
    horario: '15:30–16:00',
    icon: '🥗',
    tipo: 'opcoes',
    descricao: 'Escolha uma opção + fruta:',
    opcoes: [
      'Muffin salgado com tomate e espinafre (2 unidades) + fruta',
      'Panqueca proteica (1 unidade) + fruta',
      'Crepioca hiperproteica (1 unidade) + fruta',
      'Bolinho de frango com abóbora + fruta',
      'Salgado funcional de frango ou carne + fruta',
      'Bowl: Corn Flakes (sem açúcar) + granola + 2 bananas + iogurte natural',
    ],
  },
  {
    id: 'lanche_tarde2',
    label: 'Lanche da Tarde 2',
    horario: '18:00',
    icon: '🥤',
    tipo: 'fixo',
    descricao: 'Shake: 1 scoop de whey protein batido com leite, água de coco ou água',
    opcoes: null,
  },
  {
    id: 'jantar',
    label: 'Jantar',
    horario: 'Jantar',
    icon: '🌙',
    tipo: 'estruturado',
    descricao: 'Monte o prato:',
    opcoes: null,
    estrutura: [
      { nome: 'Proteína', detalhe: '~150g de carne, frango ou peixe (assado ou cozido de preferência)' },
      { nome: 'Carboidrato', detalhe: 'Tubérculos (3 col sopa) ou abóbora assada (3 pedaços) ou quinua (6 col sopa) ou arroz integral (5 col sopa)' },
      { nome: 'Legumes cozidos', detalhe: '1 xícara — dar preferência a vegetais cozidos à noite, menos salada crua' },
      { nome: 'Sobremesa', detalhe: 'Chocolate amargo (20g)' },
    ],
    opcoesAlternativas: null,
  },
  {
    id: 'suplementos',
    label: 'Suplementos do Dia',
    horario: 'Todo dia',
    icon: '💊',
    tipo: 'checklist',
    descricao: 'Marque o que tomou hoje:',
    opcoes: [
      'Creatina (diariamente)',
      'Whey protein (lanche da tarde — já incluído no lanche 2)',
      'Glutamina (se possível)',
    ],
  },
]
